apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleet-allocator
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: ["allocation.agones.dev"]
    resources: ["gameserverallocations"]
    verbs: ["create"]
  - apiGroups: ["autoscaling.agones.dev"]
    resources: ["fleetautoscalers"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["agones.dev"]
    resources: ["fleets", "gameservers", "gameserversets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
